services:
  recommender-system-assignment:
    build:
      context: .
      dockerfile: Dockerfile
    image: typescript
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: ["npm", "run", "start"]
